version: 2
updates:
  # GitHub Actions used in workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(ci)"
      include: "scope"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
