language: python
dist: bionic


install:
  # Required so `git describe` will definitely find a tag; see
  # https://github.com/travis-ci/travis-ci/issues/7422
  - git fetch --unshallow

matrix:
  fast_finish: true
  include:
    - name: run-lxd-example
      install:
          # Generate an SSH key to connect to test instances
          - ssh-keygen -N "" -f ~/.ssh/id_rsa
          - pip install -r requirements.txt
      script:
          - sudo apt-get remove --yes --purge lxd lxd-client
          - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - sg lxd -c "python examples/lxd.py"
    - name: run-cloudinit-integration-tests
      install:
          # Generate an SSH key to connect to test instances
          - ssh-keygen -N "" -f ~/.ssh/id_rsa
          - pip install -r requirements.txt
          - pip install pytest
      script:
          - sudo apt-get remove --yes --purge lxd lxd-client
          - sudo apt-get update -q
          - sudo apt-get install -qqy distro-info
          - sudo rm -Rf /var/lib/lxd
          - sudo snap install lxd
          - sudo lxd init --auto
          - sudo usermod -a -G lxd $USER
          - git clone https://github.com/canonical/cloud-init.git
          - cd cloud-init
          - sg lxd -c "CLOUD_INIT_CLOUD_INIT_SOURCE=ppa:cloud-init-dev/daily pytest -m ci tests/integration_tests/"
