[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.mypy]
follow_imports = "silent"
warn_unused_ignores = "true"
warn_redundant_casts = "true"
exclude=[]

[[tool.mypy.overrides]]
module = [
  "azure.*",
  "boto3",
  "botocore.*",
  "google.*",
  "googleapiclient.*",
  "ibm_vpc.*",
  "ibm_cloud_sdk_core.*",
  "ibm_platform_services.*",
  "knack.*",
  "oci.*",
  "paramiko.*",
]
ignore_missing_imports = true

[tool.ruff]
line-length = 79

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = [
  "D",   # pydocstyle
  "I",   # isort
]

[tool.ruff.lint.pydocstyle]
convention = "pep257"
