[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ['py36']

[tool.isort]
profile = "black"
line_length = 79

[tool.mypy]
follow_imports = "silent"
warn_unused_ignores = "true"
warn_redundant_casts = "true"
exclude=[]

[[tool.mypy.overrides]]
module = [
  "azure.*",
  "boto3",
  "botocore.*",
  "google.*",
  "googleapiclient.*",
  "ibm_vpc.*",
  "ibm_cloud_sdk_core.*",
  "ibm_platform_services.*",
  "knack.*",
  "oci.*",
  "paramiko.*",
  "simplestreams",
]
ignore_missing_imports = true
