name: Pycloudlib CI

on: [pull_request]

concurrency:
  group: "ci-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Run ruff and mypy checks
        run: uvx --with tox-uv tox -e ruff,mypy

  unit-tests:
    strategy:
      matrix:
        include:
          - python: "3.10"
            runner: ubuntu-22.04
            tox-env: py310
          - python: "3.12"
            runner: ubuntu-24.04
            tox-env: py312
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Run tox
        run: uvx --with tox-uv tox -e ${{ matrix.tox-env }}

  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Build rtd docs
        run: uvx --with tox-uv tox -e docs

  integration-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -qy distro-info
          sudo snap install lxd
      - name: Git checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9  # v9.0.0
      - name: Setup LXD
        uses: canonical/setup-lxd@8c6a87bfb56aa48f3fb9b830baa18562d8bfd4ee  # v1
      - name: Setup pycloudlib config and ssh key
        run: |
          ssh-keygen -P "" -q -f ~/.ssh/id_rsa
          mkdir -p ~/.config
          echo "[lxd]" > ~/.config/pycloudlib.toml
      - name: Run CI integration tests
        run: |
          uvx --with tox-uv tox -e integration-tests-ci -- --color=yes tests/integration_tests/
