name: Pycloudlib CI

on: [pull_request]

concurrency:
  group: "ci-${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  linting:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6
      - name: Run ruff and mypy checks
        run: uvx --with tox-uv tox -e ruff,mypy

  unit-tests:
    strategy:
      matrix:
        include:
          - python: "3.10"
            runner: ubuntu-22.04
            tox-env: py310
          - python: "3.12"
            runner: ubuntu-24.04
            tox-env: py312
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Git checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6
      - name: Run tox
        run: uvx --with tox-uv tox -e ${{ matrix.tox-env }}

  docs:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6
      - name: Build rtd docs
        run: uvx --with tox-uv tox -e docs

  integration-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -qy distro-info
          sudo snap install lxd
      - name: Git checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6
      - name: Setup LXD
        uses: canonical/setup-lxd@54a5806e490d92e207b57183cf111ed54bbdeff4  # v0.1.2
      - name: Setup pycloudlib config and ssh key
        run: |
          ssh-keygen -P "" -q -f ~/.ssh/id_rsa
          mkdir -p ~/.config
          echo "[lxd]" > ~/.config/pycloudlib.toml
      - name: Run CI integration tests
        run: |
          uvx --with tox-uv tox -e integration-tests-ci -- --color=yes tests/integration_tests/
