name: Pycloudlib Post Merge Check

on:
  push:
    branches:
      - main

jobs:
  post-merge-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -qqy distro-info tox
          sudo apt-get remove --yes --purge azure-cli
      - name: Initialize Pycloudlib
        env:
          GCE_CREDENTIALS_JSON: ${{ secrets.GCE_CREDENTIALS_JSON }}
          PYCLOUDLIB_TOML: ${{ secrets.PYCLOUDLIB_TOML }}
        run: |
          ssh-keygen -P "" -q -f ~/.ssh/cloudinit_id_rsa
          mkdir -p ~/.config
          echo "$GCE_CREDENTIALS_JSON" > ~/.config/gce_credentials
          echo "$PYCLOUDLIB_TOML" > ~/.config/pycloudlib.toml
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Run CI integration tests
        run: tox -e integration-tests-main-check
