name: Pycloudlib Post Merge Check

on:
  push:
    branches:
      - main

jobs:
  post-merge-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -q
          sudo apt-get install -qy distro-info
          sudo apt-get remove --yes --purge azure-cli
      - name: Initialize Pycloudlib
        env:
          GCE_CREDENTIALS_JSON: ${{ secrets.GCE_CREDENTIALS_JSON }}
          PYCLOUDLIB_TOML: ${{ secrets.PYCLOUDLIB_TOML }}
        run: |
          ssh-keygen -P "" -q -f ~/.ssh/cloudinit_id_rsa
          mkdir -p ~/.config
          echo "$GCE_CREDENTIALS_JSON" > ~/.config/gce_credentials
          echo "$PYCLOUDLIB_TOML" > ~/.config/pycloudlib.toml
      - name: Git checkout
        uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26  # v3
      - name: Install uv
        uses: astral-sh/setup-uv@d0cc045d04ccac9d8b7881df0226f9e82c39688e  # v6
      - name: Run CI integration tests
        run: |
          GOOGLE_APPLICATION_CREDENTIALS=~/.config/gce_credentials uvx --with tox-uv tox -e integration-tests-main-check \
            -- --color=yes tests/integration_tests
