name: Check Semantic Versioning
on:
  - pull_request

jobs:
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          fetch-depth: 0  # Necessary to compare with the main branch

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7.0.0
        with:
          python-version: '3.x'  # Use Python 3.x

      - name: Check version bump
        run: |
          # Fetch VERSION file from the main branch
          OLD_VERSION=$(git show origin/main:VERSION)
          # Read VERSION file from the current branch
          NEW_VERSION=$(cat VERSION)
          
          echo "Old version: $OLD_VERSION"
          echo "New version: $NEW_VERSION"
          
          pip install -r ci-requirements.txt

          # Run the version comparison Python script
          python .github/workflows/version_check.py "$OLD_VERSION" "$NEW_VERSION"

